nagios:
 image: ajeetraina/nagios
 ports:
 - 80:80
 net: "host"
 container_name: nagios-newest
 stdin_open: true
 tty: true

omsa-core:
 image: jdelaros1/openmanage-snmp
 ports:
 - 1311:1311
 - 161:162/udp
 net: "host"
 volumes:
 - {{MODULE_FOLDER}}
 container_name: omsa-core
 privileged: true
 restart: always
