nagios:
 image: ajeetraina/docker-nagios
 ports:
 - 80:80
 net: "host"
 container_name: ajeetraina/nagios
 stdin_open: true
 tty: true

omsa-core:
 image: jdelaros1/openmanage-snmp
 ports:
  - 1311:1311
  - 161:161/udp
 net: "host"
 volumes:
 - {{MODULE_FOLDER}}
 container_name: omsa-core
 privileged: true
 restart: always
